### ISSUE TITLE
Typo in Rules of participation section of webxplore page.

### ISSUE THREAD

**Issue by deep-poharkar** [nsccpccoe/nscc-frontend#81]
<img width="941" alt="Screenshot 2023-01-22 at 10 21 05 PM" src="https://user-images.githubusercontent.com/91543514/213928443-63ee747b-3f95-4f07-93dc-350f47dcb381.png">

Here spelling of ALLOWED is written as "allowd"

**Comment by deep-poharkar** [comment]
I would love to correct if you assign it to me.

**Comment by ashishbdhane** [comment]
Thank you for raising and fixing this issue.
